# Generated by Django 5.2.11 on 2026-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.CharField(max_length=255)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('personal_mail_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('differently_abled', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=100)),
                ('institution_name', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=50)),
                ('school_name', models.TextField(blank=True, null=True)),
                ('school_class', models.CharField(blank=True, max_length=50, null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_cluster', models.CharField(max_length=100)),
                ('selected_domain', models.CharField(max_length=255)),
                ('selected_domain_id', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=100)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('intern_id', models.CharField(max_length=20)),
                ('internship_duration', models.IntegerField()),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField()),
                ('application_status', models.CharField(default='Registered', max_length=100)),
                ('offer_letter_issued', models.BooleanField(default=False)),
                ('lor_issued', models.BooleanField(default=False)),
                ('completion_certificate_issued', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
